version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resource-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    networks:
      - resource-network
    depends_on:
      - db

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resource-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - resource-network
    depends_on:
      - backend

  # 数据库服务（可选，如果使用外部数据库可以移除）
  db:
    image: alpine:latest
    container_name: resource-db
    restart: unless-stopped
    volumes:
      - backend_data:/data
    networks:
      - resource-network
    command: tail -f /dev/null

  # Nginx 反向代理（生产环境）
  nginx:
    image: nginx:alpine
    container_name: resource-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - resource-network
    depends_on:
      - frontend
      - backend

volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  resource-network:
    driver: bridge