global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@your-domain.com'
  smtp_auth_username: 'alerts@your-domain.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@your-domain.com'
        subject: '[CRITICAL] 工具资源站告警'
        body: |
          告警详情:
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://localhost:5001/webhook/critical'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@your-domain.com'
        subject: '[WARNING] 工具资源站告警'
        body: |
          告警详情:
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt }}
          {{ end }}

  # 钉钉机器人告警（可选）
  - name: 'dingtalk-alerts'
    webhook_configs:
      - url: 'https://oapi.dingtalk.com/robot/send?access_token=YOUR_DINGTALK_TOKEN'
        send_resolved: true
        http_config:
          proxy_url: 'http://proxy.example.com:8080'
        title: '工具资源站告警'
        text: |
          {{ range .Alerts }}
          **告警名称**: {{ .Annotations.summary }}
          **告警描述**: {{ .Annotations.description }}
          **告警级别**: {{ .Labels.severity }}
          **告警时间**: {{ .StartsAt }}
          {{ end }}

  # 企业微信告警（可选）
  - name: 'wechat-alerts'
    wechat_configs:
      - corp_id: 'YOUR_CORP_ID'
        agent_id: 'YOUR_AGENT_ID'
        api_secret: 'YOUR_API_SECRET'
        to_user: '@all'
        message: |
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

templates:
  - '/etc/alertmanager/templates/*.tmpl'